-- Icon by Mitali - Complete Database Setup Script
-- Run this script in Supabase SQL Editor: https://supabase.com/dashboard/project/apmiabucenklyfaewoun/sql

-- ============================================================================
-- TABLE 1: ORDERS
-- ============================================================================
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  order_number VARCHAR NOT NULL UNIQUE,
  customer_name VARCHAR NOT NULL,
  customer_email VARCHAR NOT NULL,
  customer_phone VARCHAR,
  billing_address JSONB,
  shipping_address JSONB NOT NULL,
  items JSONB NOT NULL,
  total_amount DECIMAL(10, 2) NOT NULL,
  sub_total DECIMAL(10, 2),
  discount DECIMAL(10, 2),
  shipping_charges DECIMAL(10, 2),
  razorpay_order_id VARCHAR,
  razorpay_payment_id VARCHAR,
  shipment_id VARCHAR,
  refund_id VARCHAR,
  status VARCHAR DEFAULT 'pending',
  tracking_details JSONB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- TABLE 2: PRODUCTS
-- ============================================================================
CREATE TABLE IF NOT EXISTS products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  sku VARCHAR UNIQUE,
  category VARCHAR,
  images JSONB,
  show_in_lookbook BOOLEAN DEFAULT FALSE,
  stock_quantity INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- TABLE 3: BLOG POSTS
-- ============================================================================
CREATE TABLE IF NOT EXISTS blog_posts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR NOT NULL,
  slug VARCHAR NOT NULL UNIQUE,
  content TEXT NOT NULL,
  author VARCHAR,
  featured_image VARCHAR,
  excerpt TEXT,
  published BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- TABLE 4: PAGE SETTINGS
-- ============================================================================
CREATE TABLE IF NOT EXISTS page_settings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  page_name VARCHAR NOT NULL UNIQUE,
  settings JSONB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- TABLE 5: USER PROFILES (for role management)
-- ============================================================================
CREATE TABLE IF NOT EXISTS user_profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email VARCHAR NOT NULL UNIQUE,
  full_name VARCHAR,
  role VARCHAR DEFAULT 'user',
  avatar_url VARCHAR,
  is_admin BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- INDEXES (for performance)
-- ============================================================================
CREATE INDEX IF NOT EXISTS orders_customer_email_idx ON orders(customer_email);
CREATE INDEX IF NOT EXISTS orders_status_idx ON orders(status);
CREATE INDEX IF NOT EXISTS products_category_idx ON products(category);
CREATE INDEX IF NOT EXISTS blog_posts_published_idx ON blog_posts(published);
CREATE INDEX IF NOT EXISTS user_profiles_email_idx ON user_profiles(email);

-- ============================================================================
-- ROW LEVEL SECURITY POLICIES
-- ============================================================================

-- Enable RLS on all tables
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE page_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;

-- Products are readable by everyone
CREATE POLICY "Products are readable by everyone" ON products
  FOR SELECT USING (true);

-- Published blog posts are readable by everyone
CREATE POLICY "Published posts are readable" ON blog_posts
  FOR SELECT USING (published = true);

-- Authenticated users can read their own orders
CREATE POLICY "Users can read their own orders" ON orders
  FOR SELECT 
  USING (auth.uid()::text = customer_email OR auth.jwt() ->> 'role' = 'admin');

-- Users can read own profile
CREATE POLICY "Users can read own profile" ON user_profiles
  FOR SELECT 
  USING (auth.uid() = id OR auth.jwt() ->> 'role' = 'admin');

-- Page settings readable by everyone
CREATE POLICY "Page settings readable by everyone" ON page_settings
  FOR SELECT USING (true);

-- ============================================================================
-- SAMPLE DATA (Optional)
-- ============================================================================

-- Insert sample product
INSERT INTO products (name, description, price, sku, category, show_in_lookbook, stock_quantity)
VALUES (
  'Luxury Cashmere Sweater',
  'Premium hand-knitted cashmere sweater with timeless design',
  15000.00,
  'SKU-001',
  'Knitwear',
  true,
  50
) ON CONFLICT (sku) DO NOTHING;

-- Insert sample blog post
INSERT INTO blog_posts (title, slug, content, author, excerpt, published)
VALUES (
  'The Art of Sustainable Knitwear',
  'sustainable-knitwear',
  'Discover how we combine traditional knitting techniques with sustainable practices...',
  'Icon by Mitali',
  'Learn about our commitment to sustainable fashion',
  true
) ON CONFLICT (slug) DO NOTHING;

-- ============================================================================
-- VERIFICATION QUERIES (Run these to verify setup)
-- ============================================================================

-- Check tables exist
-- SELECT * FROM information_schema.tables WHERE table_schema = 'public';

-- Check RLS is enabled
-- SELECT schemaname, tablename, rowsecurity FROM pg_tables WHERE schemaname = 'public';

-- Check policies
-- SELECT schemaname, tablename, policyname, permissive, roles FROM pg_policies WHERE schemaname = 'public';
