-- Icon by Mitali - Collection Foreign Key Migration
-- Migration Date: 2026-06-03
-- Purpose: Add collections table and establish FK relationship with products

-- ============================================================================
-- TABLE 1: COLLECTIONS (NEW)
-- ============================================================================
CREATE TABLE IF NOT EXISTS collections (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR NOT NULL UNIQUE,
  description TEXT,
  image_url VARCHAR,
  display_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- TABLE 2: PRODUCTS (UPDATED)
-- ============================================================================
-- Step 1: Add collection_id column if it doesn't exist
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS collection_id BIGINT REFERENCES collections(id) ON DELETE SET NULL;

-- Step 2: Add additional product fields for better management
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS original_price DECIMAL(10, 2),
ADD COLUMN IF NOT EXISTS sizes JSONB DEFAULT '["XS", "S", "M", "L", "XL"]'::jsonb,
ADD COLUMN IF NOT EXISTS size_chart_image_url VARCHAR,
ADD COLUMN IF NOT EXISTS stock BIGINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS featured BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS show_in_lookbook BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS related_products JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS videos JSONB DEFAULT '[]'::jsonb;

-- ============================================================================
-- TABLE 3: KNITWEAR ITEMS (ADD collection_id FK)
-- ============================================================================
ALTER TABLE IF EXISTS knitwear_items 
ADD COLUMN IF NOT EXISTS collection_id BIGINT REFERENCES collections(id) ON DELETE SET NULL;

-- ============================================================================
-- INDEXES (for performance)
-- ============================================================================
CREATE INDEX IF NOT EXISTS products_collection_id_idx ON products(collection_id);
CREATE INDEX IF NOT EXISTS products_featured_idx ON products(featured);
CREATE INDEX IF NOT EXISTS collections_is_active_idx ON collections(is_active);
CREATE INDEX IF NOT EXISTS knitwear_items_collection_id_idx ON knitwear_items(collection_id);

-- ============================================================================
-- INSERT DEFAULT COLLECTIONS
-- ============================================================================
INSERT INTO collections (name, description, display_order, is_active) 
VALUES 
  ('Second Skin', 'Comfortable and breathable everyday wear', 1, TRUE),
  ('Urban Elegance', 'Contemporary designs for modern style', 2, TRUE),
  ('Seasonal Essentials', 'Collection for all seasons', 3, TRUE),
  ('Limited Edition', 'Exclusive and limited availability pieces', 4, TRUE)
ON CONFLICT (name) DO NOTHING;

-- ============================================================================
-- MIGRATION LOG
-- ============================================================================
-- Note: If you have existing products with "collection" as text:
-- 1. Manually migrate collection names to IDs using the INSERT above
-- 2. Use the UPDATE statement below to populate collection_id for existing products
-- 
-- Example migration (if you have a "collection" text column temporarily):
-- UPDATE products p
-- SET collection_id = c.id
-- FROM collections c
-- WHERE LOWER(TRIM(p.collection)) = LOWER(TRIM(c.name))
--   AND p.collection_id IS NULL
--   AND p.collection IS NOT NULL;
-- 
-- After verification, drop the old collection column:
-- ALTER TABLE products DROP COLUMN IF EXISTS collection;

-- ============================================================================
-- ROW LEVEL SECURITY FOR COLLECTIONS
-- ============================================================================
ALTER TABLE collections ENABLE ROW LEVEL SECURITY;

-- Collections readable by everyone
CREATE POLICY IF NOT EXISTS "Collections are readable by everyone" ON collections
  FOR SELECT USING (is_active = true);

-- Only authenticated users can read collections
CREATE POLICY IF NOT EXISTS "All authenticated users can read collections" ON collections
  FOR SELECT USING (auth.role() = 'authenticated');

-- Admin users can manage collections
-- This assumes admin users have a custom claim or role
-- Adjust based on your actual admin identification method
